################################################################################
#
# thunder-plugins
#
################################################################################
THUNDER_PLUGINS_VERSION = R5.2.0
THUNDER_PLUGINS_SITE = $(call github,rdkcentral,ThunderNanoServices,$(THUNDER_PLUGINS_VERSION))
THUNDER_PLUGINS_INSTALL_STAGING = YES
THUNDER_PLUGINS_DEPENDENCIES = thunder thunder-interfaces

# thunder-netflix binary package config
THUNDER_PLUGINS_OPKG_NAME = "thunder-plugins"
THUNDER_PLUGINS_OPKG_VERSION = "1.0.0"
THUNDER_PLUGINS_OPKG_ARCHITECTURE = "${BR2_ARCH}"
THUNDER_PLUGINS_OPKG_MAINTAINER = "Metrological"
THUNDER_PLUGINS_OPKG_DESCRIPTION = "Thunder plugins"

ifeq ($(BR2_CMAKE_HOST_DEPENDENCY),)
THUNDER_PLUGINS_CONF_OPTS += \
       -DCMAKE_MODULE_PATH=$(HOST_DIR)/share/cmake/Modules
endif

THUNDER_PLUGINS_CONF_OPTS += $(THUNDER_CMAKE_COMMON_OPTIONS)
THUNDER_PLUGINS_CONF_OPTS += -DBUILD_REFERENCE=${THUNDER_PLUGINS_VERSION}

ifeq ($(BR2_CMAKE_HOST_DEPENDENCY),)
THUNDER_PLUGINS_CONF_OPTS += \
       -DCMAKE_MODULE_PATH=$(HOST_DIR)/share/cmake/Modules
endif

ifeq ($(BR2_PACKAGE_THUNDER_AVS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS=ON

ifneq ($(BR2_PACKAGE_THUNDER_AVS_PLUGIN_NAME),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_NAME=$(BR2_PACKAGE_THUNDER_AVS_PLUGIN_NAME)
endif

ifeq ($(BR2_PACKAGE_THUNDER_AVS_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_AUTOSTART=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_AUTOSTART=false
endif

THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_PERSISTENT_ROOT_PATH=$(BR2_PACKAGE_THUNDER_PERSISTENT_PATH)
ifeq ($(BR2_PACKAGE_THUNDER_AVS_PLATFORM_RPI3),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_PLATFORM="rpi3"
else ifeq ($(BR2_PACKAGE_THUNDER_AVS_PLATFORM_CUSTOM),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_PLATFORM=$(BR2_PACKAGE_THUNDER_AVS_PLATFORM_CUSTOM_VALUE)
endif

ifneq ($(BR2_PACKAGE_THUNDER_AVS_DATA_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_DATA_PATH=$(BR2_PACKAGE_THUNDER_AVS_DATA_PATH)
endif

ifneq ($(BR2_PACKAGE_THUNDER_AVS_CUSTOM_ALEXA_CLIENT_CONFIG),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_ALEXA_CLIENT_CONFIG=$(call qstrip,$(BR2_PACKAGE_THUNDER_AVS_CUSTOM_ALEXA_CLIENT_CONFIG))
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_ALEXA_CLIENT_CONFIG="$(call qstrip,$(BR2_PACKAGE_THUNDER_AVS_DATA_PATH))/$(call qstrip,$(BR2_PACKAGE_THUNDER_AVS_PLUGIN_NAME))/AlexaClientSDKConfig.json"
endif

ifneq ($(BR2_PACKAGE_THUNDER_AVS_CUSTOM_SMART_SCREEN_CONFIG),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_SMART_SCREEN_CONFIG=$(call qstrip,$(BR2_PACKAGE_THUNDER_AVS_CUSTOM_SMART_SCREEN_CONFIG))
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_SMART_SCREEN_CONFIG="$(call qstrip,$(BR2_PACKAGE_THUNDER_AVS_DATA_PATH))/$(call qstrip,$(BR2_PACKAGE_THUNDER_AVS_PLUGIN_NAME))/SmartScreenSDKConfig.json"
endif

ifeq ($(BR2_PACKAGE_THUNDER_AVS_LOG_LEVEL_NONE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_LOG_LEVEL="NONE"
else ifeq ($(BR2_PACKAGE_THUNDER_AVS_LOG_LEVEL_CRITICAL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_LOG_LEVEL="CRITICAL"
else ifeq ($(BR2_PACKAGE_THUNDER_AVS_LOG_LEVEL_ERROR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_LOG_LEVEL="ERROR"
else ifeq ($(BR2_PACKAGE_THUNDER_AVS_LOG_LEVEL_WARN),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_LOG_LEVEL="WARN"
else ifeq ($(BR2_PACKAGE_THUNDER_AVS_LOG_LEVEL_DEBUG0),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_LOG_LEVEL="DEBUG0"
else ifeq ($(BR2_PACKAGE_THUNDER_AVS_LOG_LEVEL_DEBUG9),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_LOG_LEVEL="DEBUG9"
endif

ifeq ($(BR2_PACKAGE_THUNDER_AVS_AUDIOSOURCE_PORTAUDIO),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_AUDIOSOURCE="PORTAUDIO"
THUNDER_PLUGINS_DEPENDENCIES += portaudio
else ifeq ($(BR2_PACKAGE_THUNDER_AVS_AUDIOSOURCE_BLRC),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_AUDIOSOURCE="BluetoothRemoteControl"
else ifeq ($(BR2_PACKAGE_THUNDER_AVS_AUDIOSOURCE_CUSTOM),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_AUDIOSOURCE=$(BR2_PACKAGE_THUNDER_AVS_AUDIOSOURCE_CUSTOM_VALUE)
endif

ifneq ($(BR2_PACKAGE_THUNDER_AVS_AUDIOSOURCE),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_AUDIOSOURCE=$(BR2_PACKAGE_THUNDER_AVS_AUDIOSOURCE)
endif

ifeq ($(BR2_PACKAGE_THUNDER_AVS_ENABLE_SMART_SCREEN_SUPPORT),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_SMART_SCREEN_SUPPORT=ON
THUNDER_PLUGINS_DEPENDENCIES += alexa-smart-screen-sdk
ifeq ($(BR2_PACKAGE_THUNDER_AVS_ENABLE_SMART_SCREEN),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_SMART_SCREEN=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_SMART_SCREEN=false
endif
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_SMART_SCREEN_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_THUNDER_AVS_ENABLE_KWD_SUPPORT),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_KWD_SUPPORT=ON
THUNDER_PLUGINS_DEPENDENCIES += alexa-pryon-kwd
ifeq ($(BR2_PACKAGE_THUNDER_AVS_ENABLE_KWD),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_KWD=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_KWD=false
endif
ifneq ($(BR2_PACKAGE_THUNDER_AVS_CUSTOM_KWD_MODELS_PATH),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_KWD_MODELS_PATH=$(BR2_PACKAGE_THUNDER_AVS_CUSTOM_KWD_MODELS_PATH)
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_KWD_MODELS_PATH="$(call qstrip,$(BR2_PACKAGE_THUNDER_AVS_DATA_PATH))/$(call qstrip,$(BR2_PACKAGE_THUNDER_AVS_PLUGIN_NAME))/models"
endif
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_KWD_SUPPORT=OFF
endif

endif

ifeq ($(BR2_PACKAGE_THUNDER_BACKOFFICE), y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BACKOFFICE=ON
ifeq ($(BR2_PACKAGE_THUNDER_BACKOFFICE_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BACKOFFICE_AUTOSTART=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BACKOFFICE_AUTOSTART=false
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BACKOFFICE_SERVER_ADDRESS=$(BR2_PACKAGE_THUNDER_BACKOFFICE_SERVER_ADDRESS)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BACKOFFICE_SERVER_PORT=$(BR2_PACKAGE_THUNDER_BACKOFFICE_SERVER_PORT)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BACKOFFICE_CUSTOMER=$(BR2_PACKAGE_THUNDER_BACKOFFICE_CUSTOMER)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BACKOFFICE_PLATFORM=$(BR2_PACKAGE_THUNDER_BACKOFFICE_PLATFORM)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BACKOFFICE_COUNTRY=$(BR2_PACKAGE_THUNDER_BACKOFFICE_COUNTRY)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BACKOFFICE_TYPE=$(BR2_PACKAGE_THUNDER_BACKOFFICE_TYPE)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BACKOFFICE_SESSION=$(BR2_PACKAGE_THUNDER_BACKOFFICE_SESSION)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BACKOFFICE_CALLSIGN_MAPPING=$(BR2_PACKAGE_THUNDER_BACKOFFICE_CALLSIGN_MAPPING)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BACKOFFICE_STATE_MAPPING=$(BR2_PACKAGE_THUNDER_BACKOFFICE_STATE_MAPPING)
endif

ifeq ($(BR2_PACKAGE_THUNDER_CECCONTROL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_CECCONTROL=ON
ifeq ($(BR2_PACKAGE_HAS_NEXUS),y)
THUNDER_PLUGINS_CONF_OPTS += -DCEC_DEVICE_ADAPTER_IMPLEMENTATION=Nexus
else ifeq ($(BR2_PACKAGE_PLATCO_TV_BSP),y)
THUNDER_PLUGINS_CONF_OPTS += -DCEC_DEVICE_ADAPTER_IMPLEMENTATION=Amlogic
else
THUNDER_PLUGINS_CONF_OPTS += -DCEC_DEVICE_ADAPTER_IMPLEMENTATION=Linux
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_COBALT),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT=ON
THUNDER_PLUGINS_DEPENDENCIES += cobalt
ifeq ($(BR2_PACKAGE_HAS_NEXUS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_STARBOARD_CONFIGURATION_INCLUDE="third_party/starboard/wpe/brcm/arm/configuration_public.h"
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_STARBOARD_CONFIGURATION_INCLUDE="third_party/starboard/wpe/shared/configuration_public.h"
endif
ifeq ($(BR2_PACKAGE_THUNDER_COBALT_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_AUTOSTART=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_AUTOSTART=false
endif
ifeq ($(BR2_PACKAGE_THUNDER_COBALT_RESUMED),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_RESUMED=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_RESUMED=false
endif

ifeq ($(BR2_PACKAGE_THUNDER_COBALT_OUTOFPROCESS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_OUTOFPROCESS=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_OUTOFPROCESS=false
endif
ifneq ($(BR2_PACKAGE_THUNDER_COBALT_USER),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_USER=$(BR2_PACKAGE_THUNDER_COBALT_USER)
ifeq ($(BR2_PACKAGE_THUNDER_COBALT_GROUP),"")
THUNDER_COBALT_USER_GROUP=cobalt
else
THUNDER_COBALT_USER_GROUP=$(subst ",,$(BR2_PACKAGE_THUNDER_COBALT_GROUP)")
endif
ifneq ($(BR2_PACKAGE_THUNDER_CDMI_GROUP),"")
THUNDER_CDMI_GROUP=,$(subst ",,$(BR2_PACKAGE_THUNDER_CDMI_GROUP)")
endif
THUNDER_COBALT_USER=$(subst ",,$(BR2_PACKAGE_THUNDER_COBALT_USER)") -1 $(THUNDER_COBALT_USER_GROUP) -1 * - - $(subst ",,$(BR2_PACKAGE_THUNDER_PLATFORM_VIDEO_DEVICE_GROUP)"),$(subst ",,$(BR2_PACKAGE_THUNDER_GROUP)")$(THUNDER_CDMI_GROUP) cobalt
THUNDER_COBALT_PERMISSION=$(subst ",,$(BR2_PACKAGE_THUNDER_INSTALL_PATH)")/Cobalt r 0550 root $(subst ",,$(THUNDER_COBALT_USER_GROUP)") - - - - -
endif
ifneq ($(THUNDER_COBALT_USER_GROUP),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_GROUP=$(THUNDER_COBALT_USER_GROUP)
endif

ifeq ($(BR2_PACKAGE_THUNDER_COBALT_SINGLE_PLAYBACKRATE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_PLAYBACKRATES=false
endif

ifeq ($(BR2_PACKAGE_THUNDER_COBALT_RESOLUTION_720P),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_RESOLUTION=720p
else ifeq ($(BR2_PACKAGE_THUNDER_COBALT_RESOLUTION_1080P),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_RESOLUTION=1080p
else ifeq ($(BR2_PACKAGE_THUNDER_COBALT_RESOLUTION_2160P),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_RESOLUTION=2160p
endif

ifneq ($(BR2_PACKAGE_THUNDER_COBALT_OPERATOR_NAME),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_OPERATOR_NAME=$(BR2_PACKAGE_THUNDER_COBALT_OPERATOR_NAME)
endif
ifneq ($(BR2_PACKAGE_THUNDER_COBALT_SCOPE),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_SCOPE=$(BR2_PACKAGE_THUNDER_COBALT_SCOPE)
endif
ifneq ($(BR2_PACKAGE_THUNDER_COBALT_SECRET),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_SECRET=$(BR2_PACKAGE_THUNDER_COBALT_SECRET)
endif
ifneq ($(BR2_PACKAGE_THUNDER_COBALT_URL),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_URL=$(BR2_PACKAGE_THUNDER_COBALT_URL)
endif

ifneq ($(BR2_PACKAGE_THUNDER_COBALT_VIDEO_BUFFER_BUDGET),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_VIDEO_BUFFER_BUDGET=$(BR2_PACKAGE_THUNDER_COBALT_VIDEO_BUFFER_BUDGET)
endif
ifneq ($(BR2_PACKAGE_THUNDER_COBALT_AUDIO_BUFFER_BUDGET),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_AUDIO_BUFFER_BUDGET=$(BR2_PACKAGE_THUNDER_COBALT_AUDIO_BUFFER_BUDGET)
endif
ifneq ($(BR2_PACKAGE_THUNDER_COBALT_PROGRESSIVE_BUFFER_BUDGET),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_PROGRESSIVE_BUFFER_BUDGET=$(BR2_PACKAGE_THUNDER_COBALT_PROGRESSIVE_BUFFER_BUDGET)
endif
ifneq ($(BR2_PACKAGE_THUNDER_COBALT_MEDIA_GARBAGE_COLLECT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_MEDIA_GARBAGE_COLLECT=$(BR2_PACKAGE_THUNDER_COBALT_MEDIA_GARBAGE_COLLECT)
endif

endif

ifeq ($(BR2_PACKAGE_THUNDER_COMMANDER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMMANDER=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_DEVICEINFO),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DEVICEINFO=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_DISPLAYINFO),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DISPLAYINFO=ON
ifeq ($(BR2_PACKAGE_HAS_NEXUS),y)
THUNDER_PLUGINS_CONF_OPTS += -DDISPLAYINFO_IMPLEMENTATION_REPOSITORY=git@github.com:WebPlatformForEmbedded/DisplayInfo-brcm.git
endif
ifeq ($(BR2_PACKAGE_RPI_FIRMWARE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DISPLAYINFO_HDCP_LEVEL="Hdcp1X"
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_DSRESOLUTION),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DSRESOLUTION=ON
ifeq ($(BR2_PACKAGE_DSRESOLUTION_WITH_DUMMY_DSHAL), y)
THUNDER_PLUGINS_CONF_OPTS += -DDSRESOLUTION_WITH_DUMMY_DSHAL=ON
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_RESOLUTION_720P),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_RESOLUTION=720p
else ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_RESOLUTION_1080P),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_RESOLUTION=1080p50Hz
else ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_RESOLUTION_2160P),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_RESOLUTION=2160p50Hz
endif

ifeq ($(BR2_PACKAGE_THUNDER_DHCPSERVER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DHCPSERVER=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_DIALSERVER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER=ON

ifneq ($(BR2_PACKAGE_THUNDER_DIALSERVER_NAME),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_NAME="$(call qstrip,$(BR2_PACKAGE_THUNDER_DIALSERVER_NAME))"
endif

ifneq ($(BR2_PACKAGE_THUNDER_DIALSERVER_INTERFACE),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_INTERFACE="$(call qstrip,$(BR2_PACKAGE_THUNDER_DIALSERVER_INTERFACE))"
endif

ifeq ($(BR2_PACKAGE_THUNDER_HAS_YOUTUBE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_ENABLE_YOUTUBE=ON
ifeq ($(BR2_PACKAGE_THUNDER_DIALSERVER_YOUTUBE_MODE_ACTIVE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_YOUTUBE_MODE="active"
ifneq ($(BR2_PACKAGE_THUNDER_DIALSERVER_YOUTUBE_CALLSIGN),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_YOUTUBE_CALLSIGN="$(call qstrip,$(BR2_PACKAGE_THUNDER_DIALSERVER_YOUTUBE_CALLSIGN))"
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_DIALSERVER_YOUTUBE_MODE_PASSIVE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_YOUTUBE_MODE="passive"
endif
ifeq ($(BR2_PACKAGE_THUNDER_DIALSERVER_YOUTUBE_RUNTIMECHANGE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_YOUTUBE_RUNTIMECHANGE=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_YOUTUBE_RUNTIMECHANGE=false
endif
endif

ifneq ($(BR2_PACKAGE_THUNDER_DIALSERVER_NAME),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_NAME="$(call qstrip,$(BR2_PACKAGE_THUNDER_DIALSERVER_NAME))"
endif

ifeq ($(BR2_PACKAGE_THUNDER_NETFLIX),y)

ifeq ($(BR2_PACKAGE_NETFLIX5_1),y)
THUNDER_PLUGINS_CONF_OPTS += -DNETFLIX_VERSION_5_1=true
endif
ifeq ($(BR2_PACKAGE_NETFLIX52),y)
THUNDER_PLUGINS_CONF_OPTS += -DNETFLIX_VERSION_5_2=true
endif

THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_ENABLE_NETFLIX=ON
ifeq ($(BR2_PACKAGE_THUNDER_DIALSERVER_NETFLIX_MODE_ACTIVE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_NETFLIX_MODE="active"
ifneq ($(BR2_PACKAGE_THUNDER_DIALSERVER_NETFLIX_CALLSIGN),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_NETFLIX_CALLSIGN="$(call qstrip,$(BR2_PACKAGE_THUNDER_DIALSERVER_NETFLIX_CALLSIGN))"
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_DIALSERVER_NETFLIX_MODE_PASSIVE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_NETFLIX_MODE="passive"
endif
endif

endif

ifeq ($(BR2_PACKAGE_THUNDER_DICTIONARY),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DICTIONARY=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_IOCONNECTOR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_IOCONNECTOR=ON
ifneq ($(BR2_PACKAGE_THUNDER_IOCONNECTOR_PAIRING_PIN),)
    THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_IOCONNECTOR_PAIRING_PIN=${BR2_PACKAGE_THUNDER_IOCONNECTOR_PAIRING_PIN}
    THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_IOCONNECTOR_PAIRING_CALLSIGN=${BR2_PACKAGE_THUNDER_IOCONNECTOR_PAIRING_CALLSIGN}
    THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_IOCONNECTOR_PAIRING_PRODUCER=${BR2_PACKAGE_THUNDER_IOCONNECTOR_PAIRING_PRODUCER}
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_IOCONNECTOR_PINS='$(call qstrip,$(BR2_PACKAGE_THUNDER_IOCONNECTOR_PINS))'
endif

ifeq ($(BR2_PACKAGE_THUNDER_INPUTSWITCH),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_INPUTSWITCH=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_EGLTEST),y)
THUNDER_COMMON_CONF_OPTS += -DPLUGIN_EGLTEST=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_FRONTPANEL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_FRONTPANEL=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_NETWORKCONTROL),y)
ifeq ($(BR2_TARGET_GENERIC_NETWORK),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_NETWORKCONTROL_SYSTEM_NETWORK=ON
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_NETWORKCONTROL=ON
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_NETWORKCONTROL_INTERFACES='$(call qstrip,$(BR2_PACKAGE_THUNDER_NETWORKCONTROL_INTERFACES))'
endif

ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTH_CONTROL),y)
#Prevent switching bluetooth to ttyS0
export BLUETOOTH=1
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTH=ON
ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTH_BAUDRATE_HIGH),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTH_BAUDRATE=921600
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTH_BAUDRATE=115200
endif
ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTH_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTH_AUTOSTART=true
endif
ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTH_PERSISTMAC),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTH_PERSISTMAC=true
endif
ifneq ($(BR2_PACKAGE_THUNDER_BLUETOOTH_DEVICE),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTH_PORT="$(call qstrip,$(BR2_PACKAGE_THUNDER_BLUETOOTH_DEVICE))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_BLUETOOTH_FIRMWARE_DIRECTORY),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTH_FIRMWARE_DIRECTORY="$(call qstrip,$(BR2_PACKAGE_THUNDER_BLUETOOTH_FIRMWARE_DIRECTORY))"
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTH_OOP=false
THUNDER_PLUGINS_DEPENDENCIES += bluez5_utils-headers
endif

ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHREMOTECONTROL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHREMOTECONTROL=ON
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHREMOTECONTROL_CONTROLLER="BluetoothControl"
# THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHREMOTECONTROL_=${BR2_PACKAGE_THUNDER_BLUETOOTHREMOTECONTROL_FIRST_AUDIO_CHUNKSIZE}
# THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHREMOTECONTROL_=${BR2_PACKAGE_THUNDER_BLUETOOTHREMOTECONTROL_AUDIO_CHUNKSIZE}
endif

ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHSDPSERVER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHSDPSERVER=ON
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHSDPSERVER_CONTROLLER="BluetoothControl"
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHSDPSERVER_PROVIDER=${BR2_PACKAGE_THUNDER_BLUETOOTHSDPSERVER_PROVIDER}
endif

ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHAUDIO=ON
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHAUDIO_CONTROLLER="BluetoothControl"
endif

ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO_SINK),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHAUDIO_SINK=ON
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHAUDIO_SINK_LATENCY=${BR2_PACKAGE_THUNDER_BLUETOOTHAUDIOSINK_LATENCY}
ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO_SINK_CODECSBC), y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHAUDIO_SINK_CODECSBC=ON
ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO_SINK_CODECSBC_PRESET_LQ),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHAUDIO_SINK_CODECSBC_PRESET=LQ
else ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO_SINK_CODECSBC_PRESET_MQ),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHAUDIO_SINK_CODECSBC_PRESET=MQ
else ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO_SINK_CODECSBC_PRESET_HQ),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHAUDIO_SINK_CODECSBC_PRESET=HQ
else ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO_SINK_CODECSBC_PRESET_XQ),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHAUDIO_SINK_CODECSBC_PRESET=XQ
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO_SINK_SDPSERVICE), y)
# This is not an error, these settings are seen from the remote device perspective.
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHSDPSERVER_SERVICE_A2DP_AUDIO_SOURCE="BluetoothAudioSink"
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHSDPSERVER_SERVICE_A2DPAUDIOSOURCE_NAME=${BR2_PACKAGE_THUNDER_BLUETOOTHAUDIOSINK_SDPSERVICE_NAME}
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHSDPSERVER_SERVICE_A2DPAUDIOSOURCE_DESCRIPTION=${BR2_PACKAGE_THUNDER_BLUETOOTHAUDIOSINK_SDPSERVICE_DESCRIPTION}
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO_SOURCE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHAUDIO_SOURCE=ON

THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHAUDIO_SOURCE_CONNECTOR=${BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO_SOURCE_CONNECTOR}

ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO_SOURCE_CODECSBC),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHAUDIO_SOURCE_CODECSBC_MAXBITPOOL=${BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO_SOURCE_CODECSBC_MAXBITPOOL}
endif

ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHAUDIO_SOURCE_SDPSERVICE), y)
# This is not an error, these settings are seen from the remote device perspective.
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHSDPSERVER_SERVICE_A2DP_AUDIO_SINK="BluetoothAudioSource"
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHSDPSERVER_SERVICE_A2DPAUDIOSINK_NAME=${BR2_PACKAGE_THUNDER_BLUETOOTHAUDIOSOURCE_SDPSERVICE_NAME}
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHSDPSERVER_SERVICE_A2DPAUDIOSINK_DESCRIPTION=${BR2_PACKAGE_THUNDER_BLUETOOTHAUDIOSOURCE_SDPSERVICE_DESCRIPTION}
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_REMOTECONTROL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_REMOTECONTROL=ON
THUNDER_PLUGINS_CONF_OPTS += -DREMOTECONTROL_IMPLEMENTATION_REPOSITORY=https://github.com/WebPlatformForEmbedded/RemoteControl-brcm
ifeq ($(BR2_PACKAGE_THUNDER_REMOTECONTROL_DEVINPUT),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_REMOTECONTROL_DEVINPUT=ON
THUNDER_PLUGINS_DEPENDENCIES += udev
endif
ifeq ($(BR2_PACKAGE_THUNDER_REMOTECONTROL_IR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_REMOTECONTROL_IR=ON
ifneq ($(BR2_PACKAGE_THUNDER_REMOTECONTROL_IR_CODEMASK),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_REMOTECONTROL_CODEMASK="$(call qstrip,$(BR2_PACKAGE_THUNDER_REMOTECONTROL_IR_CODEMASK))"
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_REMOTECONTROL_CUSTOM_VIRTUAL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_REMOTECONTROL_CUSTOM_VIRTUAL_NAME="$(call qstrip,$(BR2_PACKAGE_THUNDER_REMOTECONTROL_CUSTOM_VIRTUAL_NAME))"
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_REMOTECONTROL_CUSTOM_VIRTUAL_MAP_FILE="$(call qstrip,$(BR2_PACKAGE_THUNDER_REMOTECONTROL_CUSTOM_VIRTUAL_MAP_FILE))"
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_RESOURCEMONITOR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_RESOURCEMONITOR=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_SNAPSHOT),y)
THUNDER_PLUGINS_DEPENDENCIES += libpng
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SNAPSHOT=ON
THUNDER_PLUGINS_CONF_OPTS += -DSNAPSHOT_IMPLEMENTATION_REPOSITORY=git@github.com:WebPlatformForEmbedded/Snapshot-brcm.git
endif
ifeq ($(BR2_PACKAGE_THUNDER_SWITCHBOARD),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SWITCHBOARD=ON
ifneq ($(BR2_PACKAGE_THUNDER_SWITCHBOARD_DEFAULT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SWITCHBOARD_DEFAULT=$(BR2_PACKAGE_THUNDER_SWITCHBOARD_DEFAULT)
endif
ifneq ($(BR2_PACKAGE_THUNDER_SWITCH_AMAZON),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SWITCH_AMAZON=ON
endif
ifneq ($(BR2_PACKAGE_THUNDER_SWITCH_COBALT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SWITCH_COBALT=ON
endif
ifneq ($(BR2_PACKAGE_THUNDER_SWITCH_NETFLIX),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SWITCH_NETFLIX=ON
endif
ifneq ($(BR2_PACKAGE_THUNDER_SWITCH_WEBKITBROWSER),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SWITCH_WEBKITBROWSER=ON
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_SYSTEMCOMMANDS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SYSTEMCOMMANDS=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_FILETRANSFER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_FILETRANSFER=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_FIRMWARECONTROL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_FIRMWARECONTROL=ON
THUNDER_PLUGINS_DEPENDENCIES += mfr-library
endif
ifeq ($(BR2_PACKAGE_THUNDER_TESTCONTROLLER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_TESTCONTROLLER=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_EXAMPLEJSONRPC),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_JSONRPC=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_EXAMPLE_DYNAMIC_LOADING),y)
THUNDER_PLUGINS_CONF_OPTS += -DEXAMPLE_DYNAMICLOADING=ON
ifeq ($(BR2_PACKAGE_THUNDER_EXAMPLE_DYNAMIC_LOADING_YIN),y)
THUNDER_PLUGINS_CONF_OPTS += -DEXAMPLE_DYNAMICLOADING_YIN=ON
ifeq ($(BR2_PACKAGE_THUNDER_EXAMPLE_DYNAMIC_LOADING_YIN_OOP),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_YIN_MODE="Local"
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_YIN_MODE="Off"
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_EXAMPLE_DYNAMIC_LOADING_YANG),y)
THUNDER_PLUGINS_CONF_OPTS += -DEXAMPLE_DYNAMICLOADING_YANG=ON
ifeq ($(BR2_PACKAGE_THUNDER_EXAMPLE_DYNAMIC_LOADING_YANG_OOP),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_YANG_MODE="Local"
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_YANG_MODE="Off"
endif
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_OUTOFPROCESSTEST),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_OUTOFPROCESS=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_TESTAUTOMATIONTOOLS),y)
THUNDER_PLUGINS_CONF_OPTS += -DTEST_AUTOMATION_TOOLS=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_TESTUTILITY),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_TESTUTILITY=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_TIMESYNC),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_TIMESYNC=ON
ifeq ($(BR2_PACKAGE_THUNDER_TIMESYNC_DEFFERED),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_TIMESYNC_DEFFERED=ON
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_VOLUMECONTROL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_VOLUMECONTROL=ON
THUNDER_PLUGINS_CONF_OPTS += -DVOLUMECONTROL_IMPLEMENTATION_REPOSITORY=git@github.com:WebPlatformForEmbedded/VolumeControl-brcm.git
endif

ifeq ($(BR2_PACKAGE_PLUGIN_RTSPCLIENT),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_RTSPCLIENT=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_WEBPA),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA=ON
THUNDER_PLUGINS_DEPENDENCIES += parodus libparodus tinyxml
ifeq ($(BR2_PACKAGE_THUNDER_WEBPA_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_AUTOSTART=true
endif
ifeq ($(BR2_PACKAGE_THUNDER_WEBPA_SERVICE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_SERVICE=true
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_PINGWAITTIME=$(BR2_PACKAGE_THUNDER_WEBPA_PINGWAITTIME)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_WEBPAURL=$(BR2_PACKAGE_THUNDER_WEBPA_WEBPAURL)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_PARODUSLOCALURL=$(BR2_PACKAGE_THUNDER_WEBPA_PARODUSLOCALURL)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_PARTENRID=$(BR2_PACKAGE_THUNDER_WEBPA_PARTENRID)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_BACKOFFMAX=$(BR2_PACKAGE_THUNDER_WEBPA_BACKOFFMAX)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_CERTPATH=$(BR2_PACKAGE_THUNDER_WEBPA_CERTPATH)
endif

ifeq ($(BR2_PACKAGE_THUNDER_WEBPA_GENERIC_ADAPTER), y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_GENERIC_ADAPTER=true
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_GENERICCLIENTURL=$(BR2_PACKAGE_THUNDER_WEBPA_GENERICCLIENTURL)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_DATAMODELFILE=$(BR2_PACKAGE_THUNDER_WEBPA_DATAMODELFILE)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_NOTIFYCONFIGFILE=$(BR2_PACKAGE_THUNDER_WEBPA_NOTIFYCONFIGFILE)
ifeq ($(BR2_PACKAGE_THUNDER_WEBPA_DEVICE_INFO),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_DEVICE_INFO=true
THUNDER_PLUGINS_DEPENDENCIES += procps-ng
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_WEBPA_CCSP), y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_CCSP=true
THUNDER_PLUGINS_DEPENDENCIES += parodus2ccsp ccspcr
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_CCSP_CLIENTURL=$(BR2_PACKAGE_THUNDER_WEBPA_CCSPCLIENTURL)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_CCSP_CONFIGFILE=$(BR2_PACKAGE_THUNDER_WEBPA_CCSP_CONFIGFILE)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_CCSP_DATAFILE=$(BR2_PACKAGE_THUNDER_WEBPA_CCSP_DATAFILE)
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_WEBPROXY),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPROXY=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_WEBSERVER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBSERVER=ON
ifneq ($(BR2_PACKAGE_THUNDER_WEBSERVER_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBSERVER_PATH=$(BR2_PACKAGE_THUNDER_WEBSERVER_PATH)
endif
ifneq ($(BR2_PACKAGE_THUNDER_WEBSERVER_PORT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBSERVER_PORT=$(BR2_PACKAGE_THUNDER_WEBSERVER_PORT)
endif
ifeq ($(BR2_PACKAGE_THUNDER_PORT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBSERVER_BRIDGE_PORT=80
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBSERVER_BRIDGE_PORT=$(BR2_PACKAGE_THUNDER_PORT)
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_WEBSHELL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBSHELL=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_WIFICONTROL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WIFICONTROL=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PERFORMANCE_MONITOR), y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PERFORMANCEMONITOR=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLAYERINFO),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PLAYERINFO=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_POWER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_POWER=ON
ifeq ($(BR2_PACKAGE_THUNDER_POWER_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_POWER_AUTOSTART=true
endif
ifneq ($(BR2_PACKAGE_THUNDER_POWER_GPIOPIN),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_POWER_GPIOPIN=$(BR2_PACKAGE_THUNDER_POWER_GPIOPIN)
endif
ifneq ($(BR2_PACKAGE_THUNDER_POWER_GPIOTYPE),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_POWER_GPIOTYPE=$(BR2_PACKAGE_THUNDER_POWER_GPIOTYPE)
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGINPROCESSCONTAINERS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PROCESSCONTAINERS=ON
ifeq ($(BR2_PACKAGE_THUNDER_PLUGINPROCESSCONTAINERS_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PROCESSCONTAINERS_AUTOSTART=true
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_PROCESSMONITOR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PROCESSMONITOR=ON
ifeq ($(BR2_PACKAGE_THUNDER_PROCESSMONITOR_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PROCESSMONITOR_AUTOSTART=true
endif
ifneq ($(BR2_PACKAGE_THUNDER_PROCESSMONITOR_EXITTIMEOUT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PROCESSMONITOR_EXITTIMEOUT=${BR2_PACKAGE_THUNDER_PROCESSMONITOR_EXITTIMEOUT}
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_STREAMER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER=ON
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_DECODERS=$(call qstrip,$(BR2_PACKAGE_THUNDER_STREAMER_DECODERS))
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST),y)
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_CABLE),y)
PLUGIN_STREAMER_IMPLEMENTATIONS += QAM
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_CABLE=ON
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_STANDARD_DVB),y)
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_CABLE_ANNEX_A),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_CABLE_ANNEX=A
else ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_CABLE_ANNEX_B),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_CABLE_ANNEX=B
else ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_CABLE_ANNEX_C),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_CABLE_ANNEX=C
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_CABLE_ANNEX=NoAnnex
endif
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_CABLE_FRONTENDS=$(call qstrip,$(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_CABLE_FRONTENDS))
endif
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_SATELLITE),y)
PLUGIN_STREAMER_IMPLEMENTATIONS += QAM
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_SATELLITE=ON
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_STANDARD_DVB),y)
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_SATELLITE_ANNEX_A),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_SATELLITE_ANNEX=A
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_SATELLITE_ANNEX=NoAnnex
endif
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_SATELLITE_FRONTENDS=$(call qstrip,$(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_SATELLITE_FRONTENDS))
endif
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_TERRESTRIAL),y)
PLUGIN_STREAMER_IMPLEMENTATIONS += QAM
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_TERRESTRIAL=ON
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_STANDARD_DVB),y)
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_TERRESTRIAL_ANNEX_A),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_TERRESTRIAL_ANNEX=A
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_TERRESTRIAL_ANNEX=NoAnnex
endif
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_TERRESTRIAL_FRONTENDS=$(call qstrip,$(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_TERRESTRIAL_FRONTENDS))
endif
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_TS_SCANNING),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_TS_SCANNING=ON
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_HOME_TS=$(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_HOME_TS)
endif
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_STANDARD_DVB),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_STANDARD=DVB
else ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_STANDARD_ATSC),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_STANDARD=ATSC
else ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_STANDARD_ISDB),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_STANDARD=ISDB
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_AAMP), y)
PLUGIN_STREAMER_IMPLEMENTATIONS += Aamp
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_AAMP_FRONTENDS=$(call qstrip,$(BR2_PACKAGE_THUNDER_STREAMER_AAMP_FRONTENDS))
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_AAMP_USE_WESTEROS_SINK),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_AAMP_WESTEROSSINK=ON
endif
THUNDER_PLUGINS_DEPENDENCIES += gst1-aamp
endif
ifeq (${BR2_PACKAGE_THUNDER_STREAMER_CENC}, y)
PLUGIN_STREAMER_IMPLEMENTATIONS += CENC
THUNDER_PLUGINS_DEPENDENCIES += gstreamer1 gst1-cencdecrypt gst1-plugins-base gst1-plugins-good
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_IMPLEMENTATIONS="$(PLUGIN_STREAMER_IMPLEMENTATIONS)"
endif

ifeq ($(BR2_PACKAGE_THUNDER_SPARK),y)
THUNDER_PLUGINS_DEPENDENCIES += spark
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SPARK=ON
ifeq ($(BR2_PACKAGE_THUNDER_SPARK_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SPARK_AUTOSTART=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SPARK_AUTOSTART=false
endif

THUNDER_PLUGINS_CONF_OPTS += -DPLATFORM_LINUX=ON
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLATFORM_THUNDER=ON
else ifeq ($(BR2_PACKAGE_WESTEROS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLATFORM_WAYLAND_EGL=ON
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_RPCLINK),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_RPCLINK=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR=ON
THUNDER_PLUGINS_DEPENDENCIES += thunder-clientlibraries
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_IMPLEMENTATION_MESA),y)
THUNDER_PLUGINS_DEPENDENCIES += mesa3d libdrm 
THUNDER_PLUGINS_CONF_OPTS += \
   -DPLUGIN_COMPOSITOR_IMPLEMENTATION=Mesa \
   -DCOMPOSITOR_DISPLAY_IMPLEMENTATION=DRM \
   -DCOMPOSITOR_BACKEND_IMPLEMENTATION=DRM \
   -DENABLE_ATOMIC=ON

ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_COMPOSITOR_OUTPUT_MODES),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_OUTPUTS='$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_COMPOSITOR_OUTPUT_MODES))'
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGBM),y)
THUNDER_PLUGINS_CONF_OPTS += -DCOMPOSITOR_BUFFER_IMPLEMENTATION=GBM
THUNDER_PLUGINS_DEPENDENCIES += libgbm
else 
THUNDER_PLUGINS_CONF_OPTS += -DCOMPOSITOR_BUFFER_IMPLEMENTATION=DRMDumb
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_IMPLEMENTATION_WESTEROS),y)
THUNDER_PLUGINS_DEPENDENCIES += westeros
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_IMPLEMENTATION=Wayland
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_SUB_IMPLEMENTATION=Westeros
endif
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_IMPLEMENTATION_WESTON),y)
THUNDER_PLUGINS_DEPENDENCIES += weston
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_IMPLEMENTATION=Wayland
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_SUB_IMPLEMENTATION=Weston
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_WESTON_OUTPUT_CONFIGS='$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_WESTON_OUTPUT_CONFIGS))'
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_WESTON_TTY_LIST='$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_WESTON_TTY_LIST))'
endif
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_IMPLEMENTATION_NEXUS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_IMPLEMENTATION=Nexus
THUNDER_PLUGINS_CONF_OPTS += -DCOMPOSITOR_IMPLEMENTATION_REPOSITORY=git@github.com:WebPlatformForEmbedded/Compositor-brcm.git
ifeq ($(BR2_PACKAGE_BCM_REFSW),y)
THUNDER_PLUGINS_DEPENDENCIES += bcm-refsw
endif
ifneq ($(BR2_PACKAGE_BCM_REFSW),y)
THUNDER_PLUGINS_CONF_OPTS += -DNEXUS_SERVER_HAS_EXTENDED_INIT=OFF
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_IMPLEMENTATION_DISPMANX),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_IMPLEMENTATION=RPI
THUNDER_PLUGINS_DEPENDENCIES += rpi-userland
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_RENDER_NODE),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_RENDER_NODE='$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_RENDER_NODE))'
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_RUNTIME_PATH),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_RUNTIME_PATH='$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_RUNTIME_PATH))'
endif
ifneq ($(BR2_PACKAGE_THUNDER_GROUP), "")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_CONNECTOR="/tmp/compositor|0770"
endif
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_OUTOFPROCESS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_OUTOFPROCESS=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_OUTOFPROCESS=false
endif
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_AUTOSTART=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_AUTOSTART=false
endif
ifeq ($(BR2_PACKAGE_HAS_NEXUS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_NXSERVER=ON
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_NEXUS_SERVER_EXTERNAL),y)
THUNDER_PLUGINS_CONF_OPTS += -DNEXUS_SERVER_EXTERNAL=ON
else
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_IRMODE),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_IRMODE="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_IRMODE))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_BOXMODE),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_BOXMODE="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_BOXMODE))"
endif
ifneq ($(BR2_PACKAGE_BCM_REFSW_SAGE_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_SAGE_PATH="$(call qstrip,$(BR2_PACKAGE_BCM_REFSW_SAGE_PATH))"
endif
ifneq ($(BR2_PACKAGE_BCM_REFSW_PAK_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_PAK_PATH="$(call qstrip,$(BR2_PACKAGE_BCM_REFSW_PAK_PATH))"
endif
ifneq ($(BR2_PACKAGE_BCM_REFSW_DRM_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_DRM_PATH="$(call qstrip,$(BR2_PACKAGE_BCM_REFSW_DRM_PATH))"
endif
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_SVP_NONE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_SVP="None"
else ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_SVP_VIDEO),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_SVP="Video"
else ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_SVP_ALL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_SVP="All"
endif

ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_GFX),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_GFX="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_GFX))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_GFX2),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_GFX2="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_GFX2))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_RESTRICTED),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_RESTRICTED="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_RESTRICTED))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_MAIN),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_MAIN="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_MAIN))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_EXPORT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_EXPORT="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_EXPORT))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_SECUREGFX),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_SECUREGFX="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_SECUREGFX))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_CLIENT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_CLIENT="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_CLIENT))"
endif
ifneq ($(BR2_PACKAGE_BCM_REFSW_HDCP1XBIN_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_HDCP1XBIN_PATH="$(call qstrip,$(BR2_PACKAGE_BCM_REFSW_HDCP1XBIN_PATH))"
endif
ifneq ($(BR2_PACKAGE_BCM_REFSW_HDCP2XBIN_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_HDCP2XBIN_PATH="$(call qstrip,$(BR2_PACKAGE_BCM_REFSW_HDCP2XBIN_PATH))"
endif

ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_ALLOW_UNAUTHENTICATED_CLIENTS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_ALLOW_UNAUTHENTICATED_CLIENTS=false
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_ALLOW_UNAUTHENTICATED_CLIENTS=true
endif
endif
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_VIRTUALINPUT),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_VIRTUALINPUT=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_NEXUS_SERVER_EXTERNAL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_HARDWAREREADY=0
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_HARDWAREREADY=${BR2_PACKAGE_THUNDER_COMPOSITOR_HARDWAREREADY}
endif

define THUNDER_COMPOSITOR_POST_TARGET_REMOVE_HEADERS
    rm -rf $(TARGET_DIR)/usr/include/Thunder
endef

ifneq ($(BR2_PACKAGE_THUNDER_INSTALL_HEADERS),y)
THUNDER_PLUGINS_POST_INSTALL_TARGET_HOOKS += THUNDER_COMPOSITOR_POST_TARGET_REMOVE_HEADERS
endif

ifeq ($(BR2_PACKAGE_THUNDER_CREATE_IPKG_TARGETS),y)
$(call SIMPLE_OPKG_TOOLS_CREATE_CPACK_METADATA,THUNDER_PLUGINS)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_CREATE_IPKG_TARGETS=ON
THUNDER_PLUGINS_CONF_OPTS += ${THUNDER_PLUGINS_OPKG_CPACK_METADATA}

THUNDER_PLUGINS_POST_BUILD_HOOKS += SIMPLE_OPKG_TOOLS_MAKE_PACKAGE
THUNDER_PLUGINS_POST_INSTALL_TARGET_HOOKS += THUNDER_PLUGINS_INSTALL_IPKG_CMDS

define THUNDER_PLUGINS_INSTALL_IPKG_CMDS
    $(eval PACKAGE_NAME_PREFIX := ${THUNDER_PLUGINS_OPKG_NAME}_${THUNDER_PLUGINS_OPKG_VERSION}_${THUNDER_PLUGINS_OPKG_ARCHITECTURE})
    $(call SIMPLE_OPKG_TOOLS_INSTALL_PACKAGE,${@D}/${PACKAGE_NAME_PREFIX}-ThunderWebKitBrowser.deb)
    $(call SIMPLE_OPKG_TOOLS_INSTALL_PACKAGE,${@D}/${PACKAGE_NAME_PREFIX}-WPEInjectedBundle.deb)

    $(call SIMPLE_OPKG_TOOLS_REMOVE_FROM_TARGET)
endef # THUNDER_PLUGINS_INSTALL_TARGET_CMDS

endif # ($(BR2_PACKAGE_THUNDER_CREATE_IPKG_TARGETS),y)

define THUNDER_PLUGINS_USERS
	${THUNDER_COBALT_USER}
endef

define THUNDER_PLUGINS_PERMISSIONS
	${THUNDER_COBALT_PERMISSION}
endef

$(eval $(cmake-package))
