################################################################################
#
# thunder-interfaces
#
################################################################################
THUNDER_INTERFACES_VERSION = 6746b11bb984b68943ed434fad37919a2e7ad436
THUNDER_INTERFACES_SITE = $(call github,rdkcentral,ThunderInterfaces,$(THUNDER_INTERFACES_VERSION))
THUNDER_INTERFACES_INSTALL_STAGING = YES
THUNDER_INTERFACES_DEPENDENCIES = thunder

THUNDER_INTERFACES_OPKG_NAME = "thunder-interfaces"
THUNDER_INTERFACES_OPKG_VERSION = "1.0.0"
THUNDER_INTERFACES_OPKG_ARCHITECTURE = "${BR2_ARCH}"
THUNDER_INTERFACES_OPKG_MAINTAINER = "Metrological"
THUNDER_INTERFACES_OPKG_DESCRIPTION = "Thunder interfaces"

THUNDER_INTERFACES_CONF_OPTS += -DBUILD_REFERENCE=${THUNDER_INTERFACES_VERSION}

ifeq ($(BR2_CMAKE_HOST_DEPENDENCY),)
THUNDER_INTERFACES_CONF_OPTS += \
       -DCMAKE_MODULE_PATH=$(HOST_DIR)/share/cmake/Modules
endif

ifeq ($(BR2_PACKAGE_THUNDER_BUILD_TYPE_DEBUG),y)
        THUNDER_INTERFACES_CONF_OPTS += -DBUILD_TYPE=Debug
else ifeq ($(BR2_PACKAGE_THUNDER_BUILD_TYPE_DEBUG_OPTIMIZED),y)
        THUNDER_INTERFACES_CONF_OPTS += -DBUILD_TYPE=DebugOptimized
else ifeq ($( BR2_PACKAGE_THUNDER_BUILD_TYPE_RELEASE_WITH_SYMBOLS),y)
        THUNDER_INTERFACES_CONF_OPTS += -DBUILD_TYPE=ReleaseSymbols
else ifeq ($(BR2_PACKAGE_THUNDER_BUILD_TYPE_RELEASE),y)
        THUNDER_INTERFACES_CONF_OPTS += -DBUILD_TYPE=Release
else ifeq ($(BR2_PACKAGE_THUNDER_BUILD_TYPE_PRODUCTION),y)
        THUNDER_INTERFACES_CONF_OPTS += -DBUILD_TYPE=Production
endif

ifeq ($(BR2_PACKAGE_THUNDER_CDM),y)
THUNDER_INTERFACES_CONF_OPTS += -DCDMI=ON
endif

$(eval $(cmake-package))
