################################################################################
#
# westeros-simpleshell
#
################################################################################

WESTEROS_SIMPLESHELL_VERSION = $(WESTEROS_VERSION)
WESTEROS_SIMPLESHELL_SITE_METHOD = $(WESTEROS_SITE_METHOD)
WESTEROS_SIMPLESHELL_SITE = $(WESTEROS_SITE)
WESTEROS_SIMPLESHELL_INSTALL_STAGING = YES
WESTEROS_SIMPLESHELL_SUBDIR = simpleshell/
WESTEROS_SIMPLESHELL_AUTORECONF = YES
WESTEROS_SIMPLESHELL_AUTORECONF_OPTS = "-Icfg"

WESTEROS_SIMPLESHELL_DEPENDENCIES = wayland libglib2

define WESTEROS_SIMPLESHELL_RUN_AUTOCONF
	mkdir -p $(@D)/simpleshell/cfg
	mkdir -p $(@D)/simpleshell/m4
endef
WESTEROS_SIMPLESHELL_PRE_CONFIGURE_HOOKS += WESTEROS_SIMPLESHELL_RUN_AUTOCONF


define WESTEROS_SIMPLESHELL_GENERATE_PROTOCOLS
	$(call WESTEROS_GENERATE_WAYLAND_PROTOCOLS,$(@D)/simpleshell/protocol)
endef


WESTEROS_SIMPLESHELL_PRE_BUILD_HOOKS += WESTEROS_SIMPLESHELL_GENERATE_PROTOCOLS

WESTEROS_SIMPLESHELL_POST_PATCH_HOOKS += WESTEROS_APPLY_PID_LOG_PATCH

$(eval $(autotools-package))
