################################################################################
#
# thunder-tools
#
################################################################################
HOST_THUNDER_TOOLS_VERSION = 1ea5895e595ca58fac126acf14e170fb2765f5d5
HOST_THUNDER_TOOLS_SITE = $(call github,rdkcentral,ThunderTools,$(HOST_THUNDER_TOOLS_VERSION))
HOST_THUNDER_TOOLS_INSTALL_STAGING = YES
HOST_THUNDER_TOOLS_INSTALL_TARGET = NO
HOST_THUNDER_TOOLS_DEPENDENCIES = host-cmake host-python3 host-python-jsonref

HOST_THUNDER_TOOLS_CONF_OPTS += -DCMAKE_INSTALL_PREFIX="$(HOST_DIR)/usr"
HOST_THUNDER_TOOLS_CONF_OPTS += -DPROXYSTUB_GENERATOR_ENABLE_SECURITY=$(if $(BR2_PACKAGE_THUNDER_TOOLS_PROXYSTUB_SECURITY),ON,OFF)
HOST_THUNDER_TOOLS_CONF_OPTS += -DPROXYSTUB_GENERATOR_ENABLE_COHERENCY=$(if $(BR2_PACKAGE_THUNDER_TOOLS_PROXYSTUB_COHERENCY),ON,OFF)
HOST_THUNDER_TOOLS_CONF_OPTS += -DJSON_GENERATOR_ENABLE_STATS=$(if $(BR2_PACKAGE_THUNDER_ENABLE_JSONRPC_STATS),ON,OFF)

$(eval $(host-cmake-package))
