
ifeq ($(BR2_PACKAGE_GST1_PLUGINS_BASE_LIB_OPENGL_LIBGBM),y)
GST1_PLUGINS_BASE_WINSYS_LIST += gbm
GST1_PLUGINS_BASE_DEPENDENCIES += libgbm libgudev

define GST1_PLUGINS_BASE_ENSURE_GBM_DEPENDECIES_ARE_BUILD
	@$(call MESSAGE,"Ensuring libgbm and libgudev are built")
    $(MAKE) -C $(BASE_DIR) libgbm libgudev
endef
GST1_PLUGINS_BASE_PRE_CONFIGURE_HOOKS += GST1_PLUGINS_BASE_ENSURE_GBM_DEPENDECIES_ARE_BUILD
endif

ifeq ($(BR2_PACKAGE_GST1_PLUGINS_BASE_LIB_OPENGL_LIBEGL),y)
GST1_PLUGINS_BASE_WINSYS_LIST += egl

define GST1_PLUGINS_BASE_ENSURE_EGL_DEPENDECIES_ARE_BUILD
	@$(call MESSAGE,"Ensuring libegl is built")
    $(MAKE) -C $(BASE_DIR) libegl
endef
GST1_PLUGINS_BASE_PRE_CONFIGURE_HOOKS += GST1_PLUGINS_BASE_ENSURE_EGL_DEPENDECIES_ARE_BUILD

endif
