
################################################################################
#
# thunder-amazon
#
################################################################################

THUNDER_AMAZON_VERSION = e3c687f8e6483c11ba450056803891e4e7401b63
THUNDER_AMAZON_SITE_METHOD = git
THUNDER_AMAZON_SITE = git@github.com:Metrological/WPEPluginAmazon.git
THUNDER_AMAZON_INSTALL_STAGING = YES
THUNDER_AMAZON_DEPENDENCIES = thunder amazon-ignition

THUNDER_AMAZON_SUPPORTS_IN_SOURCE_BUILD = NO

THUNDER_AMAZON_CONF_OPTS += \
    -DBUILD_REFERENCE=${THUNDER_AMAZON_VERSION} \
    -DPLUGIN_AMAZON_PRIME_DTID=${BR2_PACKAGE_THUNDER_AMAZON_DTID} \
    -DPLUGIN_AMAZON_PRIME_MANUFACTURER=${BR2_PACKAGE_THUNDER_AMAZON_MANUFACTURER} \
    -DPLUGIN_AMAZON_PRIME_MODEL_NAME=${BR2_PACKAGE_THUNDER_AMAZON_MODEL} \
    -DPLUGIN_AMAZON_PRIME_CHIPSET_NAME=${BR2_PACKAGE_THUNDER_AMAZON_CHIPSET}

ifeq ($(BR2_PACKAGE_THUNDER_AMAZON_AUTOSTART),y)
THUNDER_AMAZON_CONF_OPTS += -DPLUGIN_AMAZON_PRIME_AUTOSTART=ON
endif

ifneq ($(BR2_PACKAGE_THUNDER_AMAZON_INSTALL_PATH_OVERRIDE),"")
THUNDER_AMAZON_CONF_OPTS += -DPLUGIN_AMAZON_PRIME_INSTALL_PATH=${BR2_PACKAGE_THUNDER_AMAZON_INSTALL_PATH_OVERRIDE}
else
THUNDER_AMAZON_CONF_OPTS += -DPLUGIN_AMAZON_PRIME_INSTALL_PATH=${BR2_PACKAGE_AMAZON_IGNITION_IG_INSTALL_PATH}
endif

ifneq ($(BR2_PACKAGE_THUNDER_AMAZON_USER),"")
THUNDER_AMAZON_CONF_OPTS += -DPLUGIN_AMAZON_PRIME_NAME=$(BR2_PACKAGE_THUNDER_AMAZON_USER)
endif

ifneq ($(BR2_PACKAGE_THUNDER_AMAZON_GROUP),"")
THUNDER_AMAZON_CONF_OPTS += -DPLUGIN_AMAZON_PRIME_GROUP=$(BR2_PACKAGE_THUNDER_AMAZON_GROUP)
endif

ifneq ($(BR2_PACKAGE_THUNDER_AMAZON_CA_BUNDLE_PATH),"")
THUNDER_AMAZON_CONF_OPTS += -DPLUGIN_AMAZON_PRIME_CA_BUNDLE_PATH=$(BR2_PACKAGE_THUNDER_AMAZON_CA_BUNDLE_PATH)
endif

ifneq ($(BR2_PACKAGE_THUNDER_AMAZON_FRAGMENT_CACHE_SIZE),"")
THUNDER_AMAZON_CONF_OPTS += -DPLUGIN_AMAZON_PRIME_FRAGMENT_CACHE_SIZE=$(BR2_PACKAGE_THUNDER_AMAZON_FRAGMENT_CACHE_SIZE)
endif

ifneq ($(BR2_PACKAGE_THUNDER_AMAZON_LOG_LEVEL),"")
THUNDER_AMAZON_CONF_OPTS += -DPLUGIN_AMAZON_PRIME_LOG_LEVEL=$(BR2_PACKAGE_THUNDER_AMAZON_LOG_LEVEL)
endif

ifeq ($(BR2_PACKAGE_THUNDER_DEBUG),y)
THUNDER_AMAZON_CONF_OPTS += -DCMAKE_BUILD_TYPE=Debug
endif

$(eval $(cmake-package))
