ifeq ($(BR2_PACKAGE_THUNDER_TEST_CYCLICINSPECTOR),y)
THUNDER_CONF_OPTS += -DTHUNDER_TEST_APPS=ON -DTHUNDER_TEST_CYCLICINSPECTOR=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_TEST_LOADER),y)
THUNDER_CONF_OPTS += -DTHUNDER_TEST_APPS=ON -DTHUNDER_TEST_LOADER=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_NETWORKTEST),y)
THUNDER_CONF_OPTS += -DTHUNDER_TEST_APPS=ON -DTHUNDER_TEST_NETWORKTEST=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_TEST_RPCLINK),y)
THUNDER_CONF_OPTS += -DTHUNDER_TEST_RPCLINK=ON -DTHUNDER_RPC=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_LINUX_ONEWIRE),y)
THUNDER_CONF_OPTS += -DTHUNDER_TEST_APPS=ON -DTHUNDER_TEST_LINUX1W=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_TEST_UNITTESTS),y)
THUNDER_DEPENDENCIES += gtest
THUNDER_CONF_OPTS += -DBUILD_TESTS=ON
endif
