################################################################################
#
# thunder-plugins
#
################################################################################
THUNDER_PLUGINS_VERSION = 788250f93b41b18040b6a1527d987bfab915cc23
THUNDER_PLUGINS_SITE = $(call github,rdkcentral,ThunderNanoServices,$(THUNDER_PLUGINS_VERSION))
THUNDER_PLUGINS_INSTALL_STAGING = YES
THUNDER_PLUGINS_DEPENDENCIES = thunder thunder-interfaces thunder-clientlibraries

# thunder-netflix binary package config
THUNDER_PLUGINS_OPKG_NAME = "thunder-plugins"
THUNDER_PLUGINS_OPKG_VERSION = "1.0.0"
THUNDER_PLUGINS_OPKG_ARCHITECTURE = "${BR2_ARCH}"
THUNDER_PLUGINS_OPKG_MAINTAINER = "Metrological"
THUNDER_PLUGINS_OPKG_DESCRIPTION = "WPEFramework plugins"

THUNDER_PLUGINS_CONF_OPTS += -DBUILD_REFERENCE=${THUNDER_PLUGINS_VERSION}

ifeq ($(BR2_PACKAGE_THUNDER_BUILD_TYPE_DEBUG),y)
        THUNDER_PLUGINS_CONF_OPTS += -DBUILD_TYPE=Debug
else ifeq ($(BR2_PACKAGE_THUNDER_BUILD_TYPE_DEBUG_OPTIMIZED),y)
        THUNDER_PLUGINS_CONF_OPTS += -DBUILD_TYPE=DebugOptimized
else ifeq ($( BR2_PACKAGE_THUNDER_BUILD_TYPE_RELEASE_WITH_SYMBOLS),y)
        THUNDER_PLUGINS_CONF_OPTS += -DBUILD_TYPE=ReleaseSymbols
else ifeq ($(BR2_PACKAGE_THUNDER_BUILD_TYPE_RELEASE),y)
        THUNDER_PLUGINS_CONF_OPTS += -DBUILD_TYPE=Release
else ifeq ($(BR2_PACKAGE_THUNDER_BUILD_TYPE_PRODUCTION),y)
        THUNDER_PLUGINS_CONF_OPTS += -DBUILD_TYPE=Production
endif
# libprovision

ifeq ($(BR2_PACKAGE_THUNDER_COBALT),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT=ON
THUNDER_PLUGINS_DEPENDENCIES += cobalt
ifeq ($(BR2_PACKAGE_HAS_NEXUS),y)
THUNDER_PLUGINS_CONF_OPTS += -DTHUNDER_PLUGIN_COBALT_STARBOARD_CONFIGURATION_INCLUDE="third_party/starboard/wpe/brcm/arm/configuration_public.h"
else
THUNDER_PLUGINS_CONF_OPTS += -DTHUNDER_PLUGIN_COBALT_STARBOARD_CONFIGURATION_INCLUDE="third_party/starboard/wpe/rpi/configuration_public.h"
endif
ifeq ($(BR2_PACKAGE_THUNDER_COBALT_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_AUTOSTART=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_AUTOSTART=false
endif
ifeq ($(BR2_PACKAGE_THUNDER_COBALT_OUTOFPROCESS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_OUTOFPROCESS=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_OUTOFPROCESS=false
endif
ifneq ($(BR2_PACKAGE_THUNDER_COBALT_USER),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_USER=$(BR2_PACKAGE_THUNDER_COBALT_USER)
endif
ifneq ($(BR2_PACKAGE_THUNDER_COBALT_GROUP),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_GROUP=$(BR2_PACKAGE_THUNDER_COBALT_GROUP)
endif

ifeq ($(BR2_PACKAGE_THUNDER_COBALT_SINGLE_PLAYBACKRATE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_PLAYBACKRATES=false
endif

ifeq ($(BR2_PACKAGE_THUNDER_COBALT_RESOLUTION_720P),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_RESOLUTION=720p
else ifeq ($(BR2_PACKAGE_THUNDER_COBALT_RESOLUTION_1080P),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_RESOLUTION=1080p
else ifeq ($(BR2_PACKAGE_THUNDER_COBALT_RESOLUTION_2160P),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_RESOLUTION=2160p
endif

ifneq ($(BR2_PACKAGE_THUNDER_COBALT_OPERATOR_NAME),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_OPERATOR_NAME=$(BR2_PACKAGE_THUNDER_COBALT_OPERATOR_NAME)
endif
ifneq ($(BR2_PACKAGE_THUNDER_COBALT_SCOPE),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_SCOPE=$(BR2_PACKAGE_THUNDER_COBALT_SCOPE)
endif
ifneq ($(BR2_PACKAGE_THUNDER_COBALT_SECRET),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COBALT_SECRET=$(BR2_PACKAGE_THUNDER_COBALT_SECRET)
endif

endif

ifeq ($(BR2_PACKAGE_THUNDER_COMMANDER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMMANDER=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_DEVICEINFO),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DEVICEINFO=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_DISPLAYINFO),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DISPLAYINFO=ON
THUNDER_PLUGINS_CONF_OPTS += -DDISPLAYINFO_IMPLEMENTATION_REPOSITORY=git@github.com:WebPlatformForEmbedded/DisplayInfo-brcm.git
ifeq ($(BR2_PACKAGE_RPI_FIRMWARE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DISPLAYINFO_HDCP_LEVEL="Hdcp1X"
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_DSRESOLUTION),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DSRESOLUTION=ON
ifeq ($(BR2_PACKAGE_DSRESOLUTION_WITH_DUMMY_DSHAL), y)
THUNDER_PLUGINS_CONF_OPTS += -DDSRESOLUTION_WITH_DUMMY_DSHAL=ON
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_RESOLUTION_720P),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_RESOLUTION=720p
else ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_RESOLUTION_1080P),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_RESOLUTION=1080p50Hz
else ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_RESOLUTION_2160P),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_RESOLUTION=2160p50Hz
endif

ifeq ($(BR2_PACKAGE_THUNDER_DHCPSERVER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DHCPSERVER=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_DIALSERVER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER=ON

ifneq ($(BR2_PACKAGE_THUNDER_DIALSERVER_NAME),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_NAME="$(call qstrip,$(BR2_PACKAGE_THUNDER_DIALSERVER_NAME))"
endif

ifeq ($(BR2_PACKAGE_THUNDER_HAS_YOUTUBE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_ENABLE_YOUTUBE=ON
ifeq ($(BR2_PACKAGE_THUNDER_DIALSERVER_YOUTUBE_MODE_ACTIVE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_YOUTUBE_MODE="active"
ifneq ($(BR2_PACKAGE_THUNDER_DIALSERVER_YOUTUBE_CALLSIGN),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_YOUTUBE_CALLSIGN="$(call qstrip,$(BR2_PACKAGE_THUNDER_DIALSERVER_YOUTUBE_CALLSIGN))"
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_DIALSERVER_YOUTUBE_MODE_PASSIVE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_YOUTUBE_MODE="passive"
endif
ifeq ($(BR2_PACKAGE_THUNDER_DIALSERVER_YOUTUBE_RUNTIMECHANGE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_YOUTUBE_RUNTIMECHANGE=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_YOUTUBE_RUNTIMECHANGE=false
endif
endif

ifneq ($(BR2_PACKAGE_THUNDER_DIALSERVER_NAME),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_NAME="$(call qstrip,$(BR2_PACKAGE_THUNDER_DIALSERVER_NAME))"
endif

ifeq ($(BR2_PACKAGE_THUNDER_NETFLIX),y)

ifeq ($(BR2_PACKAGE_NETFLIX5_1),y)
THUNDER_PLUGINS_CONF_OPTS += -DNETFLIX_VERSION_5_1=true
endif
ifeq ($(BR2_PACKAGE_NETFLIX52),y)
THUNDER_PLUGINS_CONF_OPTS += -DNETFLIX_VERSION_5_2=true
endif

THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_ENABLE_NETFLIX=ON
ifeq ($(BR2_PACKAGE_THUNDER_DIALSERVER_NETFLIX_MODE_ACTIVE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_NETFLIX_MODE="active"
ifneq ($(BR2_PACKAGE_THUNDER_DIALSERVER_NETFLIX_CALLSIGN),"")
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_NETFLIX_CALLSIGN="$(call qstrip,$(BR2_PACKAGE_THUNDER_DIALSERVER_NETFLIX_CALLSIGN))"
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_DIALSERVER_NETFLIX_MODE_PASSIVE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DIALSERVER_NETFLIX_MODE="passive"
endif
endif

endif

ifeq ($(BR2_PACKAGE_THUNDER_DICTIONARY),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_DICTIONARY=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_IOCONNECTOR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_IOCONNECTOR=ON
ifneq ($(BR2_PACKAGE_THUNDER_IOCONNECTOR_PAIRING_PIN),)
    THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_IOCONNECTOR_PAIRING_PIN=${BR2_PACKAGE_THUNDER_IOCONNECTOR_PAIRING_PIN}
    THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_IOCONNECTOR_PAIRING_CALLSIGN=${BR2_PACKAGE_THUNDER_IOCONNECTOR_PAIRING_CALLSIGN}
    THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_IOCONNECTOR_PAIRING_PRODUCER=${BR2_PACKAGE_THUNDER_IOCONNECTOR_PAIRING_PRODUCER}
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_IOCONNECTOR_PINS='$(call qstrip,$(BR2_PACKAGE_THUNDER_IOCONNECTOR_PINS))'
endif

ifeq ($(BR2_PACKAGE_THUNDER_INPUTSWITCH),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_INPUTSWITCH=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_EGLTEST),y)
THUNDER_COMMON_CONF_OPTS += -DPLUGIN_EGLTEST=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_FRONTPANEL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_FRONTPANEL=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_NETWORKCONTROL),y)
ifeq ($(BR2_TARGET_GENERIC_NETWORK),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_NETWORKCONTROL_SYSTEM_NETWORK=ON
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_NETWORKCONTROL=ON
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_NETWORKCONTROL_INTERFACES='$(call qstrip,$(BR2_PACKAGE_THUNDER_NETWORKCONTROL_INTERFACES))'
endif

ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTH),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTH=ON
ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTH_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTH_AUTOSTART=true
endif
ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTH_PERSISTMAC),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTH_PERSISTMAC=true
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTH_OOP=false
THUNDER_PLUGINS_DEPENDENCIES += bluez5_utils
endif

ifeq ($(BR2_PACKAGE_THUNDER_BLUETOOTHREMOTECONTROL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_BLUETOOTHREMOTECONTROL=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_REMOTECONTROL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_REMOTECONTROL=ON
ifeq ($(BR2_PACKAGE_THUNDER_REMOTECONTROL_DEVINPUT),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_REMOTECONTROL_DEVINPUT=ON
THUNDER_PLUGINS_DEPENDENCIES += udev
endif
ifeq ($(BR2_PACKAGE_THUNDER_REMOTECONTROL_IR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_REMOTECONTROL_IR=ON
ifneq ($(BR2_PACKAGE_THUNDER_REMOTECONTROL_IR_CODEMASK),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_REMOTECONTROL_CODEMASK="$(call qstrip,$(BR2_PACKAGE_THUNDER_REMOTECONTROL_IR_CODEMASK))"
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_REMOTECONTROL_CUSTOM_VIRTUAL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_REMOTECONTROL_CUSTOM_VIRTUAL_NAME="$(call qstrip,$(BR2_PACKAGE_THUNDER_REMOTECONTROL_CUSTOM_VIRTUAL_NAME))"
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_REMOTECONTROL_CUSTOM_VIRTUAL_MAP_FILE="$(call qstrip,$(BR2_PACKAGE_THUNDER_REMOTECONTROL_CUSTOM_VIRTUAL_MAP_FILE))"
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_RESOURCEMONITOR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_RESOURCEMONITOR=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_SNAPSHOT),y)
THUNDER_PLUGINS_DEPENDENCIES += libpng
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SNAPSHOT=ON
THUNDER_PLUGINS_CONF_OPTS += -DSNAPSHOT_IMPLEMENTATION_REPOSITORY=git@github.com:WebPlatformForEmbedded/Snapshot-brcm.git
endif
ifeq ($(BR2_PACKAGE_THUNDER_SYSTEMCOMMANDS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SYSTEMCOMMANDS=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_FILETRANSFER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_FILETRANSFER=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_FIRMWARECONTROL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_FIRMWARECONTROL=ON
THUNDER_PLUGINS_DEPENDENCIES += mfr-library
endif
ifeq ($(BR2_PACKAGE_THUNDER_TESTCONTROLLER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_TESTCONTROLLER=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_EXAMPLEJSONRPC),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_JSONRPC=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_OUTOFPROCESSTEST),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_OUTOFPROCESS=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_TESTUTILITY),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_TESTUTILITY=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_TIMESYNC),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_TIMESYNC=ON
ifeq ($(BR2_PACKAGE_THUNDER_TIMESYNC_DEFFERED),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_TIMESYNC_DEFFERED=ON
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_VOLUMECONTROL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_VOLUMECONTROL=ON
THUNDER_PLUGINS_CONF_OPTS += -DVOLUMECONTROL_IMPLEMENTATION_REPOSITORY=git@github.com:WebPlatformForEmbedded/VolumeControl-brcm.git
endif

ifeq ($(BR2_PACKAGE_PLUGIN_RTSPCLIENT),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_RTSPCLIENT=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_WEBPA),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA=ON
THUNDER_PLUGINS_DEPENDENCIES += parodus libparodus tinyxml
ifeq ($(BR2_PACKAGE_THUNDER_WEBPA_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_AUTOSTART=true
endif
ifeq ($(BR2_PACKAGE_THUNDER_WEBPA_SERVICE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_SERVICE=true
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_PINGWAITTIME=$(BR2_PACKAGE_THUNDER_WEBPA_PINGWAITTIME)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_WEBPAURL=$(BR2_PACKAGE_THUNDER_WEBPA_WEBPAURL)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_PARODUSLOCALURL=$(BR2_PACKAGE_THUNDER_WEBPA_PARODUSLOCALURL)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_PARTENRID=$(BR2_PACKAGE_THUNDER_WEBPA_PARTENRID)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_BACKOFFMAX=$(BR2_PACKAGE_THUNDER_WEBPA_BACKOFFMAX)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_CERTPATH=$(BR2_PACKAGE_THUNDER_WEBPA_CERTPATH)
endif

ifeq ($(BR2_PACKAGE_THUNDER_WEBPA_GENERIC_ADAPTER), y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_GENERIC_ADAPTER=true
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_GENERICCLIENTURL=$(BR2_PACKAGE_THUNDER_WEBPA_GENERICCLIENTURL)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_DATAMODELFILE=$(BR2_PACKAGE_THUNDER_WEBPA_DATAMODELFILE)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_NOTIFYCONFIGFILE=$(BR2_PACKAGE_THUNDER_WEBPA_NOTIFYCONFIGFILE)
ifeq ($(BR2_PACKAGE_THUNDER_WEBPA_DEVICE_INFO),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_DEVICE_INFO=true
THUNDER_PLUGINS_DEPENDENCIES += procps-ng
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_WEBPA_CCSP), y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_CCSP=true
THUNDER_PLUGINS_DEPENDENCIES += parodus2ccsp
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_CCSP_CLIENTURL=$(BR2_PACKAGE_THUNDER_WEBPA_CCSPCLIENTURL)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_CCSP_CONFIGFILE=$(BR2_PACKAGE_THUNDER_WEBPA_CCSP_DATAFILE)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPA_CCSP_DATAFILE=$(BR2_PACKAGE_THUNDER_WEBPA_CCSP_CONFIGFILE)
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_WEBPROXY),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBPROXY=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_WEBSERVER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBSERVER=ON
ifneq ($(BR2_PACKAGE_THUNDER_WEBSERVER_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBSERVER_PATH=$(BR2_PACKAGE_THUNDER_WEBSERVER_PATH)
endif
ifneq ($(BR2_PACKAGE_THUNDER_WEBSERVER_PORT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBSERVER_PORT=$(BR2_PACKAGE_THUNDER_WEBSERVER_PORT)
endif
ifeq ($(BR2_PACKAGE_THUNDER_PORT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBSERVER_BRIDGE_PORT=80
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBSERVER_BRIDGE_PORT=$(BR2_PACKAGE_THUNDER_PORT)
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_WEBSHELL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WEBSHELL=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_WIFICONTROL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_WIFICONTROL=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PERFORMANCE_MONITOR), y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PERFORMANCEMONITOR=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLAYERINFO),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PLAYERINFO=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_POWER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_POWER=ON
ifeq ($(BR2_PACKAGE_THUNDER_POWER_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_POWER_AUTOSTART=true
endif
ifneq ($(BR2_PACKAGE_THUNDER_POWER_GPIOPIN),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_POWER_GPIOPIN=$(BR2_PACKAGE_THUNDER_POWER_GPIOPIN)
endif
ifneq ($(BR2_PACKAGE_THUNDER_POWER_GPIOTYPE),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_POWER_GPIOTYPE=$(BR2_PACKAGE_THUNDER_POWER_GPIOTYPE)
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGINPROCESSCONTAINERS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PROCESSCONTAINERS=ON
ifeq ($(BR2_PACKAGE_THUNDER_PLUGINPROCESSCONTAINERS_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PROCESSCONTAINERS_AUTOSTART=true
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_PROCESSMONITOR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PROCESSMONITOR=ON
ifeq ($(BR2_PACKAGE_THUNDER_PROCESSMONITOR_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PROCESSMONITOR_AUTOSTART=true
endif
ifneq ($(BR2_PACKAGE_THUNDER_PROCESSMONITOR_EXITTIMEOUT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_PROCESSMONITOR_EXITTIMEOUT=${BR2_PACKAGE_THUNDER_PROCESSMONITOR_EXITTIMEOUT}
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_STREAMER),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER=ON
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_DECODERS=$(call qstrip,$(BR2_PACKAGE_THUNDER_STREAMER_DECODERS))
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST),y)
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_CABLE),y)
PLUGIN_STREAMER_IMPLEMENTATIONS += QAM
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_CABLE=ON
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_STANDARD_DVB),y)
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_CABLE_ANNEX_A),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_CABLE_ANNEX=A
else ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_CABLE_ANNEX_B),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_CABLE_ANNEX=B
else ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_CABLE_ANNEX_C),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_CABLE_ANNEX=C
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_CABLE_ANNEX=NoAnnex
endif
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_CABLE_FRONTENDS=$(call qstrip,$(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_CABLE_FRONTENDS))
endif
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_SATELLITE),y)
PLUGIN_STREAMER_IMPLEMENTATIONS += QAM
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_SATELLITE=ON
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_STANDARD_DVB),y)
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_SATELLITE_ANNEX_A),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_SATELLITE_ANNEX=A
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_SATELLITE_ANNEX=NoAnnex
endif
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_SATELLITE_FRONTENDS=$(call qstrip,$(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_SATELLITE_FRONTENDS))
endif
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_TERRESTRIAL),y)
PLUGIN_STREAMER_IMPLEMENTATIONS += QAM
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_TERRESTRIAL=ON
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_STANDARD_DVB),y)
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_TERRESTRIAL_ANNEX_A),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_TERRESTRIAL_ANNEX=A
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_TERRESTRIAL_ANNEX=NoAnnex
endif
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_TERRESTRIAL_FRONTENDS=$(call qstrip,$(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_TERRESTRIAL_FRONTENDS))
endif
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_TS_SCANNING),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_TS_SCANNING=ON
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_HOME_TS=$(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_HOME_TS)
endif
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_STANDARD_DVB),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_STANDARD=DVB
else ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_STANDARD_ATSC),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_STANDARD=ATSC
else ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_BROADCAST_STANDARD_ISDB),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_BROADCAST_STANDARD=ISDB
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_AAMP), y)
PLUGIN_STREAMER_IMPLEMENTATIONS += Aamp
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_AAMP_FRONTENDS=$(call qstrip,$(BR2_PACKAGE_THUNDER_STREAMER_AAMP_FRONTENDS))
ifeq ($(BR2_PACKAGE_THUNDER_STREAMER_AAMP_USE_WESTEROS_SINK),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_AAMP_WESTEROSSINK=ON
endif
THUNDER_PLUGINS_DEPENDENCIES += gst1-aamp
endif
ifeq (${BR2_PACKAGE_THUNDER_STREAMER_CENC}, y)
PLUGIN_STREAMER_IMPLEMENTATIONS += CENC
THUNDER_PLUGINS_DEPENDENCIES += gstreamer1 gst1-cencdecrypt gst1-plugins-base gst1-plugins-good
endif
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_STREAMER_IMPLEMENTATIONS="$(PLUGIN_STREAMER_IMPLEMENTATIONS)"
endif

ifeq ($(BR2_PACKAGE_THUNDER_SPARK),y)
THUNDER_PLUGINS_DEPENDENCIES += spark
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SPARK=ON
ifeq ($(BR2_PACKAGE_THUNDER_SPARK_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SPARK_AUTOSTART=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_SPARK_AUTOSTART=false
endif

THUNDER_PLUGINS_CONF_OPTS += -DPLATFORM_LINUX=ON
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLATFORM_WPEFRAMEWORK=ON
else ifeq ($(BR2_PACKAGE_WESTEROS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLATFORM_WAYLAND_EGL=ON
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_RPCLINK),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_RPCLINK=ON
endif
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR=ON
ifneq ($(BR2_PACKAGE_BCM_REFSW),y)
THUNDER_PLUGINS_CONF_OPTS += -DNEXUS_SERVER_HAS_EXTENDED_INIT=OFF
endif
ifeq ($(BR2_PACKAGE_WESTEROS),y)
THUNDER_PLUGINS_DEPENDENCIES += westeros
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_IMPLEMENTATION=Wayland
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_SUB_IMPLEMENTATION=Westeros
else ifeq ($(BR2_PACKAGE_WESTON),y)
THUNDER_PLUGINS_DEPENDENCIES += weston
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_IMPLEMENTATION=Wayland
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_SUB_IMPLEMENTATION=Weston
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_WESTON_OUTPUT_CONFIGS='$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_WESTON_OUTPUT_CONFIGS))'
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_WESTON_TTY_LIST='$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_WESTON_TTY_LIST))'
else ifeq  ($(BR2_PACKAGE_BCM_REFSW),y)
THUNDER_PLUGINS_DEPENDENCIES += bcm-refsw
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_IMPLEMENTATION=Nexus
THUNDER_PLUGINS_CONF_OPTS += -DCOMPOSITOR_IMPLEMENTATION_REPOSITORY=git@github.com:WebPlatformForEmbedded/Compositor-brcm.git
else ifeq  ($(BR2_PACKAGE_HAS_NEXUS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_IMPLEMENTATION=Nexus
THUNDER_PLUGINS_CONF_OPTS += -DCOMPOSITOR_IMPLEMENTATION_REPOSITORY=git@github.com:WebPlatformForEmbedded/Compositor-brcm.git
else ifeq  ($(BR2_PACKAGE_RPI_FIRMWARE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_IMPLEMENTATION=RPI
else
$(error Missing a compositor implemtation, please provide one or disable PLUGIN_COMPOSITOR)
endif
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_OUTOFPROCESS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_OUTOFPROCESS=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_OUTOFPROCESS=false
endif
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_AUTOSTART),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_AUTOSTART=true
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_AUTOSTART=false
endif
ifeq ($(BR2_PACKAGE_HAS_NEXUS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_NXSERVER=ON
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_NEXUS_SERVER_EXTERNAL),y)
THUNDER_PLUGINS_CONF_OPTS += -DNEXUS_SERVER_EXTERNAL=ON
else
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_IRMODE),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_IRMODE="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_IRMODE))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_BOXMODE),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_BOXMODE="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_BOXMODE))"
endif
ifneq ($(BR2_PACKAGE_BCM_REFSW_SAGE_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_SAGE_PATH="$(call qstrip,$(BR2_PACKAGE_BCM_REFSW_SAGE_PATH))"
endif
ifneq ($(BR2_PACKAGE_BCM_REFSW_PAK_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_PAK_PATH="$(call qstrip,$(BR2_PACKAGE_BCM_REFSW_PAK_PATH))"
endif
ifneq ($(BR2_PACKAGE_BCM_REFSW_DRM_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_DRM_PATH="$(call qstrip,$(BR2_PACKAGE_BCM_REFSW_DRM_PATH))"
endif
ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_SVP_NONE),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_SVP="None"
else ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_SVP_VIDEO),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_SVP="Video"
else ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_SVP_ALL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_SVP="All"
endif

ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_GFX),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_GFX="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_GFX))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_GFX2),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_GFX2="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_GFX2))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_RESTRICTED),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_RESTRICTED="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_RESTRICTED))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_MAIN),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_MAIN="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_MAIN))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_EXPORT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_EXPORT="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_EXPORT))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_SECUREGFX),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_SECUREGFX="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_SECUREGFX))"
endif
ifneq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_CLIENT),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_MEMORY_CLIENT="$(call qstrip,$(BR2_PACKAGE_THUNDER_COMPOSITOR_MEMORY_CLIENT))"
endif
ifneq ($(BR2_PACKAGE_BCM_REFSW_HDCP1XBIN_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_HDCP1XBIN_PATH="$(call qstrip,$(BR2_PACKAGE_BCM_REFSW_HDCP1XBIN_PATH))"
endif
ifneq ($(BR2_PACKAGE_BCM_REFSW_HDCP2XBIN_PATH),)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_HDCP2XBIN_PATH="$(call qstrip,$(BR2_PACKAGE_BCM_REFSW_HDCP2XBIN_PATH))"
endif


ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_ALLOW_UNAUTHENTICATED_CLIENTS),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_ALLOW_UNAUTHENTICATED_CLIENTS=false
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_ALLOW_UNAUTHENTICATED_CLIENTS=true
endif
endif
endif
ifeq ($(BR2_PACKAGE_THUNDER_VIRTUALINPUT),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_VIRTUALINPUT=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_COMPOSITOR_NEXUS_SERVER_EXTERNAL),y)
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_HARDWAREREADY=0
else
THUNDER_PLUGINS_CONF_OPTS += -DPLUGIN_COMPOSITOR_HARDWAREREADY=${BR2_PACKAGE_THUNDER_COMPOSITOR_HARDWAREREADY}
endif

define THUNDER_COMPOSITOR_POST_TARGET_REMOVE_HEADERS
    rm -rf $(TARGET_DIR)/usr/include/WPEFramework
endef

ifneq ($(BR2_PACKAGE_THUNDER_INSTALL_HEADERS),y)
THUNDER_PLUGINS_POST_INSTALL_TARGET_HOOKS += THUNDER_COMPOSITOR_POST_TARGET_REMOVE_HEADERS
endif

endif

ifeq ($(BR2_PACKAGE_THUNDER_CREATE_IPKG_TARGETS),y)
$(call SIMPLE_OPKG_TOOLS_CREATE_CPACK_METADATA,THUNDER_PLUGINS)
THUNDER_PLUGINS_CONF_OPTS += -DTHUNDER_CREATE_IPKG_TARGETS=ON
THUNDER_PLUGINS_CONF_OPTS += ${THUNDER_PLUGINS_OPKG_CPACK_METADATA}

THUNDER_PLUGINS_POST_BUILD_HOOKS += SIMPLE_OPKG_TOOLS_MAKE_PACKAGE
THUNDER_PLUGINS_POST_INSTALL_TARGET_HOOKS += THUNDER_PLUGINS_INSTALL_IPKG_CMDS

define THUNDER_PLUGINS_INSTALL_IPKG_CMDS
    $(eval PACKAGE_NAME_PREFIX := ${THUNDER_PLUGINS_OPKG_NAME}_${THUNDER_PLUGINS_OPKG_VERSION}_${THUNDER_PLUGINS_OPKG_ARCHITECTURE})
    $(call SIMPLE_OPKG_TOOLS_INSTALL_PACKAGE,${@D}/${PACKAGE_NAME_PREFIX}-WPEFrameworkWebKitBrowser.deb)
    $(call SIMPLE_OPKG_TOOLS_INSTALL_PACKAGE,${@D}/${PACKAGE_NAME_PREFIX}-WPEInjectedBundle.deb)

    $(call SIMPLE_OPKG_TOOLS_REMOVE_FROM_TARGET)
endef # THUNDER_PLUGINS_INSTALL_TARGET_CMDS

endif # ($(BR2_PACKAGE_THUNDER_CREATE_IPKG_TARGETS),y)

$(eval $(cmake-package))
