################################################################################
#
# wpeframework-doofah
#
################################################################################
WPEFRAMEWORK_DOOFAH_VERSION = b4833390d0754f171114282dc37b95f5fdf535356
WPEFRAMEWORK_DOOFAH_SITE_METHOD = git
WPEFRAMEWORK_DOOFAH_SITE = git@github.com:Metrological/ThunderDoofah.git
WPEFRAMEWORK_DOOFAH_INSTALL_STAGING = NO
WPEFRAMEWORK_DOOFAH_DEPENDENCIES = wpeframework

ifeq ($(BR2_CMAKE_HOST_DEPENDENCY),)
WPEFRAMEWORK_DOOFAH_CONF_OPTS += \
       -DCMAKE_MODULE_PATH=$(HOST_DIR)/share/cmake/Modules
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DOOFAH_AUTOSTART),y)
WPEFRAMEWORK_DOOFAH_CONF_OPTS += -DPLUGIN_DOOFAH_AUTOSTART=true
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_DOOFAH_CONNECTOR_CONFIG),"")
WPEFRAMEWORK_DOOFAH_CONF_OPTS += -DPLUGIN_DOOFAH_CONNECTOR_CONFIG=$(BR2_PACKAGE_WPEFRAMEWORK_DOOFAH_CONNECTOR_CONFIG)
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_DOOFAH_ENDPOINT),"")
WPEFRAMEWORK_DOOFAH_CONF_OPTS += -DPLUGIN_DOOFAH_DEVICE_ADDRESS=$(BR2_PACKAGE_WPEFRAMEWORK_DOOFAH_ENDPOINT)
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DOOFAH_PERIPHERAL_BLE),y)
WPEFRAMEWORK_DOOFAH_CONF_OPTS += -DPLUGIN_DOOFAH_PERIPHERAL=ble
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DOOFAH_PERIPHERAL_IR),y)
WPEFRAMEWORK_DOOFAH_CONF_OPTS += -DPLUGIN_DOOFAH_PERIPHERAL=ir
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DOOFAH_PERIPHERAL_ROOT),y)
WPEFRAMEWORK_DOOFAH_CONF_OPTS += -DPLUGIN_DOOFAH_PERIPHERAL=root
endif

$(eval $(cmake-package))
