################################################################################
#
# thunder-netflix
#
################################################################################

THUNDER_NETFLIX_VERSION = 7b7cf7db7ee9fb2cfdb07ad5f3640eeb8cb6b102
ifeq ($(BR2_PACKAGE_NETFLIX50),y)
THUNDER_NETFLIX_CONF_OPTS += -DNETFLIX_VERSION_5=true
THUNDER_NETFLIX_CONF_OPTS += -DNETFLIX_VERSION_5_0=true
THUNDER_NETFLIX_DEPENDENCIES = thunder netflix50
endif
ifeq ($(BR2_PACKAGE_NETFLIX5_1),y)
THUNDER_NETFLIX_CONF_OPTS += -DNETFLIX_VERSION_5=true
THUNDER_NETFLIX_CONF_OPTS += -DNETFLIX_VERSION_5_1=true
THUNDER_NETFLIX_DEPENDENCIES = thunder netflix
endif
ifeq ($(BR2_PACKAGE_NETFLIX52),y)
THUNDER_NETFLIX_CONF_OPTS += -DNETFLIX_VERSION_5=true
THUNDER_NETFLIX_CONF_OPTS += -DNETFLIX_VERSION_5_2=true
THUNDER_NETFLIX_DEPENDENCIES = thunder netflix52
endif

THUNDER_NETFLIX_SITE_METHOD = git
THUNDER_NETFLIX_SITE = git@github.com:WebPlatformForEmbedded/WPEPluginNetflix.git
THUNDER_NETFLIX_INSTALL_STAGING = YES

# thunder-netflix binary package config
THUNDER_NETFLIX_OPKG_NAME = "thunder-netflix"
THUNDER_NETFLIX_OPKG_VERSION = "1.0.0"
THUNDER_NETFLIX_OPKG_ARCHITECTURE = "${BR2_ARCH}"
THUNDER_NETFLIX_OPKG_MAINTAINER = "Metrological"
THUNDER_NETFLIX_OPKG_DESCRIPTION = "Thunder Netflix plugin"

THUNDER_NETFLIX_CONF_OPTS += -DBUILD_REFERENCE=${THUNDER_NETFLIX_VERSION}

# TODO: Do not have THUNDER versioning yet
# THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_VERSION="$(WEBBRIDGE_BUILD_VERSION)-dev"

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_AUTOSTART),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_AUTOSTART=true
else
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_AUTOSTART=false
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_MODEL),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_MODEL="$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_MODEL))"
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_FRIENDLY_NAME),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_FRIENDLY_NAME="$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_FRIENDLY_NAME))"
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_SUSPEND_TIMEOUT),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_SUSPENDTIMEOUT="$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_SUSPEND_TIMEOUT))"
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_RESUME_TIMEOUT),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_RESUMETIMEOUT="$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_RESUME_TIMEOUT))"
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_VERSION_POSTFIX),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_DEV_POSTFIX="$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_VERSION_POSTFIX))"
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_FULLHD),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_FULLHD=true
else
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_FULLHD=false
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_HIGHRESUI),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_HIGHRESUI=true
else
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_HIGHRESUI=false
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_KEY_REPEAT_DELAY),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_KEYREPEATDELAY="$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_KEY_REPEAT_DELAY))"
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_APPBOOTKEY),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_APPBOOTKEY="$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_APPBOOTKEY))"
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_DEVICE_KEYS),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_DEVICE_KEYS="$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_DEVICE_KEYS))"
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_AVC_HIGH),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_AVC_HIGH=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_HDR10),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_HDR10=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_DOLBY_VISION),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_DOLBY_VISION=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_HEVC),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_HEVC=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_VP9_P0),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_VP9_PROFILE_0=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_VP9_P2),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_VP9_PROFILE_2=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_VP9_HDR),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_VP9_HDR=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_DDP2),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_DDP2=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_DDP5_1),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_DDP5_1=ON
endif

ifeq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_DOLBY_ATMOS),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_DOLBY_ATMOS=ON
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_DEFAULT_LAUGUAGE),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_LAUGUAGE=$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_DEFAULT_LAUGUAGE))
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_VIDEO_BUFFER_SIZE),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_VIDEO_BUFFER_SIZE=$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_VIDEO_BUFFER_SIZE))
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_AUDIO_BUFFER_SIZE),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_AUDIO_BUFFER_SIZE=$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_AUDIO_BUFFER_SIZE))
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_DISK_CACHE_SIZE),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_DISK_CACHE_SIZE=$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_DISK_CACHE_SIZE))
endif

ifneq ($(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_SURFACE_CACHE_SIZE),"")
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_SURFACE_CACHE_SIZE=$(call qstrip,$(BR2_PACKAGE_THUNDER_PLUGIN_NETFLIX_SURFACE_CACHE_SIZE))
endif

ifeq  ($(BR2_PACKAGE_RPI_FIRMWARE),y)
ifeq ($(BR2_PACKAGE_NETFLIX5),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_SPLASH_IMAGE_FORMAT=PNG
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_ENABLE_AUDIO_DOWNMIX=true
endif
ifeq ($(BR2_PACKAGE_NETFLIX52),y)
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_SPLASH_IMAGE_FORMAT=PNG
THUNDER_NETFLIX_CONF_OPTS += -DPLUGIN_ENABLE_AUDIO_DOWNMIX=true
endif
endif

ifeq ($(BR2_PACKAGE_THUNDER_CREATE_IPKG_TARGETS),y)

THUNDER_NETFLIX_CONF_OPTS += -DTHUNDER_CREATE_IPKG_TARGETS=ON

$(call SIMPLE_OPKG_TOOLS_CREATE_CPACK_METADATA,THUNDER_NETFLIX)
THUNDER_NETFLIX_CONF_OPTS += ${THUNDER_NETFLIX_OPKG_CPACK_METADATA}

THUNDER_NETFLIX_POST_BUILD_HOOKS += SIMPLE_OPKG_TOOLS_MAKE_PACKAGE

define THUNDER_NETFLIX_INSTALL_TARGET_CMDS
	@# install package
	$(call SIMPLE_OPKG_TOOLS_INSTALL_PACKAGE,\
	${@D}/${THUNDER_NETFLIX_OPKG_NAME}_${THUNDER_NETFLIX_OPKG_VERSION}_${THUNDER_NETFLIX_OPKG_ARCHITECTURE}.deb)
endef # THUNDER_NETFLIX_INSTALL_TARGET_CMDS

endif # ($(BR2_PACKAGE_THUNDER_CREATE_IPKG_TARGETS),y)

$(eval $(cmake-package))

