################################################################################
#
# westeros-simplebuffer
#
################################################################################

WESTEROS_SIMPLEBUFFER_VERSION = $(WESTEROS_VERSION)
WESTEROS_SIMPLEBUFFER_SITE_METHOD = $(WESTEROS_SITE_METHOD)
WESTEROS_SIMPLEBUFFER_SITE = $(WESTEROS_SITE)
WESTEROS_SIMPLEBUFFER_INSTALL_STAGING = YES
WESTEROS_SIMPLEBUFFER_SUBDIR = simplebuffer/
WESTEROS_SIMPLEBUFFER_AUTORECONF = YES
WESTEROS_SIMPLEBUFFER_AUTORECONF_OPTS = "-Icfg"

WESTEROS_SIMPLEBUFFER_DEPENDENCIES = wayland libglib2

define WESTEROS_SIMPLEBUFFER_RUN_AUTOCONF
	mkdir -p $(@D)/simplebuffer/cfg
	mkdir -p $(@D)/simplebuffer/m4
endef
WESTEROS_SIMPLEBUFFER_PRE_CONFIGURE_HOOKS += WESTEROS_SIMPLEBUFFER_RUN_AUTOCONF

define WESTEROS_SIMPLEBUFFER_GENERATE_PROTOCOLS
	$(call WESTEROS_GENERATE_WAYLAND_PROTOCOLS,$(@D)/simplebuffer/protocol)
endef

WESTEROS_SIMPLEBUFFER_PRE_BUILD_HOOKS += WESTEROS_SIMPLEBUFFER_GENERATE_PROTOCOLS

WESTEROS_SIMPLEBUFFER_POST_PATCH_HOOKS += WESTEROS_APPLY_PID_LOG_PATCH

$(eval $(autotools-package))
