THUNDER_LAUNCHER_VERSION = R3.2
THUNDER_LAUNCHER_SITE_METHOD = git
THUNDER_LAUNCHER_SITE = git@github.com:WebPlatformForEmbedded/WPEPluginLauncher.git
THUNDER_LAUNCHER_INSTALL_STAGING = YES
THUNDER_LAUNCHER_DEPENDENCIES = thunder thunder-interfaces

THUNDER_LAUNCHER_CONF_OPTS += -DBUILD_REFERENCE=${THUNDER_LAUNCHER_VERSION}

$(eval $(cmake-package))

