WPEFRAMEWORK_LAUNCHER_VERSION = 00845360df433b2943d00824bce8c9d339938461
WPEFRAMEWORK_LAUNCHER_SITE = $(call github,WebPlatformForEmbedded,WPEPluginLauncher,$(WPEFRAMEWORK_LAUNCHER_VERSION))
WPEFRAMEWORK_LAUNCHER_INSTALL_STAGING = YES
WPEFRAMEWORK_LAUNCHER_DEPENDENCIES = wpeframework wpeframework-interfaces

WPEFRAMEWORK_LAUNCHER_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_LAUNCHER_VERSION}

$(eval $(cmake-package))

